### ISSUE TITLE
Unable to install on Ubuntu

### ISSUE THREAD

**Issue by iinjamul** [erxes/erxes#4736]
Tried to install on Ubuntu local/production server using 
official [documentation](https://docs.erxes.io/docs/category/deployment) -

Ubuntu Version - 22.04 and 23
Environment: Localhost and Production Server

The Db Images seems running fine but
the UI docker images keeps crashing and restarting in loop.

Error Message (docker logs image_id):

╔══════════════════════════════════════════════╗
║                                              ║
║   Erxes collects anonymous usage analytics   ║
║   to help improve Erxes for all users.       ║
║                                              ║
║                                              ║
╚══════════════════════════════════════════════╝
/erxes/packages/api-utils/src/serviceDiscovery.js:10
    throw new Error('ENABLED_SERVICES_JSON environment variable is not configured.');
    ^

Error: ENABLED_SERVICES_JSON environment variable is not configured.
    at Object.<anonymous> (/erxes/packages/api-utils/src/serviceDiscovery.js:10:11)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/erxes/packages/gateway/src/redis.js:4:28)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)

Node.js v18.17.1

**Comment by mendorshikh** [comment]
@iinjamul Please join our discord channel and ask. Thanks!

**Comment by iinjamul** [comment]
Fixed

**Comment by vinyll** [comment]
Where is this fixed?
I'm on Discord to discuss about this but the error still occurs in December
